services:
  - type: web
    name: ironforge-backend
    runtime: node
    repo: https://github.com/mamme234/Gym-Trainer-
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
